preprocess:
  input: data/raw/diabetes.csv
  output: s3://lab1-s3-yana/data/processed/data.csv

train : 
  data : s3://lab1-s3-yana/data/processed/data.csv
  model_path : models/model.pkl
  random_state : 42
  n_estimators: 100
  max_depth: 5

aws :
  aws_access_key_id: ****
  aws_secret_access_key: ***
  region_name: eu-west-3

mlflow:
  MLFLOW_TRACKING_URI: http://15.188.78.74:5000/
